newPRWelcomeComment: >
  感謝您對我們當地語系化內容的貢獻！ 
  所有內容來稿都必須遵循下列方針：
  1. [Microsoft 語言樣式指南](HTTPs://www.microsoft.com/Language/StyleGuides)：說明將英文翻譯成其他語言時的語順。
  2. [Microsoft 語言入口網站](HTTPs://www.microsoft.com/language) 提供不同 Microsoft 產品中，英文對照其對應語言的技術相關詞彙翻譯。
  若要加入我們持續成長的當地語系化社群，請先前往 [Community Localization Wiki (當地語系化社群 Wiki)](https://github.com/Microsoft/Localization/wiki)，深入了解 Community Localization Program (當地語系化社群計劃) 及其他可以參與我們計劃的方法。此頁面也提供 PR 核准程序及一些 <PR 管理> 提示。
  請持續參與，衝高您在我們 [Contributors' Leaderboard (參與者排行榜)](https://microsoftl10n.github.io/) 中的排名，我們將會依據您的 <當地語系化> 貢獻點數提供獎勵！

  Microsoft 全球開發人員關係小組
